# Generated by Django 3.1.5 on 2021-01-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conscious_level', models.CharField(max_length=100, null=True)),
                ('general_state', models.PositiveSmallIntegerField(null=True)),
                ('hematoma_volume', models.PositiveSmallIntegerField(null=True)),
                ('coagupathy', models.BooleanField(default=False)),
                ('takes_anticoagulants', models.BooleanField(default=False)),
                ('time_passed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surname',
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(null=True, to='web.Diagnosis'),
        ),
    ]
