# Generated by Django 3.1.5 on 2021-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_treatment_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='time_passed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
