# Generated by Django 3.1.5 on 2021-01-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='snapshot',
            field=models.ImageField(null=True, upload_to='snapshots'),
        ),
    ]
