# Generated by Django 3.1.5 on 2021-01-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210113_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_injury',
            field=models.BooleanField(default=False),
        ),
    ]
