# Generated by Django 3.1.5 on 2021-01-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_treatment_is_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='general_state',
        ),
    ]
