# Generated by Django 3.1.5 on 2021-01-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_treatment_general_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='has_stroke_symptoms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='neurological_deficit',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='conscious_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='is_injury',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
