# Generated by Django 3.1.5 on 2021-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210117_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(to='web.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='temporary_contraindications',
            field=models.ManyToManyField(to='web.TemporaryContraindications'),
        ),
    ]
