# Generated by Django 3.1.5 on 2021-01-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210118_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='conscious_level',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='neurological_deficit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
