# Generated by Django 3.1.5 on 2021-01-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210118_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contacts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='text_to_onclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temporarycontraindications',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporarycontraindications',
            name='text_to_onclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.doctor'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hematoma_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='is_injury',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.patient'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='time_passed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
