# Generated by Django 3.1.5 on 2021-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210118_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default='Фамилия Имя Отчество', max_length=100),
        ),
    ]
