# Generated by Django 3.1.5 on 2021-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_doctor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='media/BaseProfilePhoto.svd', null=True, upload_to=''),
        ),
    ]
