# Generated by Django 3.1.5 on 2021-01-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_doctor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuronetPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.PositiveSmallIntegerField()),
                ('confidence', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='BaseProfilePhoto.svd', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='treatment',
            name='prediction',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.neuronetprediction'),
            preserve_default=False,
        ),
    ]
