# Generated by Django 3.1.5 on 2021-01-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20210120_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='prediction',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.neuronetprediction'),
        ),
    ]
