# Generated by Django 3.1.5 on 2021-01-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20210120_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prediction',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.neuronetprediction'),
        ),
    ]
